# Render.com deployment configuration
services:
  - type: web
    name: telegram-deployment-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        value: https://telegram-deployment-bot.onrender.com
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: "3.11"
    autoDeploy: true
    disk:
      name: deployment-files
      mountPath: /app
      sizeGB: 1
    healthCheckPath: /health
    plan: free
